name: docker-build-master

on:
  push:
    branches: [ master ]
    paths-ignore:  # stop README etc. changes from auto-building
      - '.gitignore'
      - '.github/workflows/docker-latest.yml'
      - '.dockerignore'
      - 'jenkins/**'
      - 'cleverspeech/**'
      - 'cleverspeech'
      - 'README.md'
      - 'LICENSE'
      - 'VERSION'
      - 'docker/Dockerfile.latest'
      - 'docker/Dockerfile.dev.latest'
  workflow_dispatch:
jobs:
  docker-build-master:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}

      - name: Login to NVIDIA nvcr.io
        uses: docker/login-action@v1
        with:
          registry: nvcr.io
          username: $oauthtoken
          password: ${{ secrets.NVCR_API_KEY }}

#      - name: Login to Public AWS ECR
#        uses: docker/login-action@v1
#        with:
#          registry: public.ecr.aws
#          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          password: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: |
            dijksterhuis/cleverspeech:${{ github.sha }}
            dijksterhuis/cleverspeech:latest
#            public.ecr.aws/w4s1p0b6/cleverspeech:latest
          no-cache: true
          build-args: branch=master
          push: true
          pull: true
          file: ./docker/Dockerfile.build

