name: docker-build

on:
  push:
    branches: [ master ]
    paths-ignore:  # stop README etc. changes from auto-building
      - '.gitignore'
      - '.github/workflows/docker-latest.yml'
      - '.dockerignore'
      - 'jenkins/**'
      - 'cleverspeech/**'
      - 'cleverspeech'
      - 'README.md'
      - 'LICENSE'
      - 'VERSION'
      - 'docker/Dockerfile.latest'
  workflow_dispatch:
jobs:
  docker-full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: |
            dijksterhuis/cleverspeech:latest
            dijksterhuis/cleverspeech:${{ github.sha }}
          no-cache: true
          push: true
          pull: true
          file: ./docker/Dockerfile.build
      - name: Login to Public AWS ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
      - name: Push to AWS public ECR
        env:
          AWS_IMAGE_REPO: public.ecr.aws/w4s1p0b6/cleverspeech
        run: |
          docker tag -t dijksterhuis/cleverspeech:latest ${AWS_IMAGE_REPO}:latest
          docker tag -t dijksterhuis/cleverspeech:${{ github.sha }} ${AWS_IMAGE_REPO}:${{ github.sha }}
          docker push --all-tags ${AWS_IMAGE_REPO}

