name: docker-latest-master

on:
  # == build when api changes detected
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:  
      - 'cleverspeech/**'
      - 'cleverspeech'
      - '.github/workflows/docker-latest-master.yml'
      - 'docker/Dockerfile.latest'

jobs:
  docker-latest-master:
    runs-on: ubuntu-latest
    steps:

      # https://github.community/t/add-short-sha-to-github-context/16418/11
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: |
            dijksterhuis/cleverspeech:${{ steps.slug.outputs.sha8 }}
            dijksterhuis/cleverspeech:latest
          no-cache: true
          build-args: |
            "branch=master"
            "base_image_tag=latest"
          push: true
          pull: true
          file: ./docker/Dockerfile.latest
          
